const List<String> ouagaNeighborhoods = [
  'Bilbalogo', 'Saint Léon', 'Zangouettin', 'Tiedpalgo',
  'Koulouba', 'Kamsonghin', 'Samandin', 'Gounghin Sud',
  'Gandin', 'Kouritega', 'Mankougoudou', 'Paspanga',
  'Ouidi', 'Larlé', 'Kologh Naba', 'Dapoya 2', 'Nemnin',
  'Niogsin', 'Hamdalaye', 'Gounghin Nord', 'Baoghin',
  'Camp militaire', 'Naababpougo', 'Kienbaoghin', 'Zongo',
  'Koumdayonré', 'Nonsin', 'Rimkieta', 'Tampouy', 'Kilwin',
  'Tanghin', 'Sambin barrage', 'Somgandé', 'Zone industrielle',
  'Nioko 2', 'Bendogo', 'Toukin', 'Zogona', 'Wemtenga',
  'Dagnoën', 'Ronsin', 'Kalgondin', 'Cissin', 'Kouritega',
  'Pissy', 'Nagrin', 'Yaoghin', 'Sandogo', 'Kankasin',
  'Boassa', 'Zaghtouli', 'Zongo Nabitega', 'Sogpèlcé',
  'Bissighin', 'Bassinko', 'Dar-es-Salam', 'Silmiougou',
  'Gantin', 'Bangpooré', 'Larlé Wéogo', 'Marcoussis',
  'Silmiyiri', 'Wob Riguéré', 'Ouapassi', 'Kossodo',
  'Wayalghin', 'Godin', 'Nioko 1', 'Dassosgo', 'Taabtega',
  'Dassasgo', 'Yemtenga', 'Karpala', 'Balkuy', 'Lanoayiri',
  'Dayongo', 'Ouidtenga'
];
